# -*- coding: utf-8 -*-
"""perception_hacker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8irf5-I0Uct1WIgV3p3lhp8I2QewWM5
"""

!pip install transformers textblob vaderSentiment yake

from transformers import pipeline
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from yake import KeywordExtractor

user_input = {
    "linkedin_summary": "I'm a data science student passionate about solving real-world problems using machine learning and AI.",
    "github_readme": "This repo contains projects related to NLP, LLMs and perception modeling.",
    "tweets": [
        "Just finished an amazing GenAI workshop at IITM!",
        "Need help building my ML portfolio. DMs open.",
        "Learning transformers from scratch. #AI"
    ]
}

summarizer=pipeline("summarization",model="facebook/bart-large-cnn")

analyzer=SentimentIntensityAnalyzer()

kw_extractor=KeywordExtractor()

content = user_input["linkedin_summary"] + " " + user_input["github_readme"] + " " + " ".join(user_input["tweets"])

summary=summarizer(content,max_length=40,min_length=30,do_sample=False)[0]['summary_text']

sentiment_score=analyzer.polarity_scores(content)

from transformers import pipeline
pipe=pipeline("text2text-generation",model="google/flan-t5-large")

keywords = kw_extractor.extract_keywords(content)
top_keywords = [kw for kw, score in keywords[:5]]
prompt = "Summarize the public online perception of a person based on this content:\n\n" + content + "\n\nPerception Summary:"
output = pipe(prompt, max_length=100, do_sample=False)[0]["generated_text"]

print("🧠 AI Perception Summary:")
print(output)

print("\n💬 Sentiment Analysis:")
print(sentiment_score)

print("\n🔑 Top Perceived Keywords:")
print(top_keywords)